//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class MeleeEnemy : Enemy
{
	private float meleeRange = 10;
	
	void Update () 
	{
		if (health != maxHealth)
			HealthBar.localScale = new Vector3 (0.0033f * health / maxHealth, .0033f, .0033f);

		float distanceFromPlayer = (Camera.main.transform.position - transform.position).magnitude;

		if(distanceFromPlayer < meleeRange && timefromLastShot > weapon.fireRate)
		{
			Player.player1.SendMessage("ApplyDamage",5,SendMessageOptions.DontRequireReceiver);
			if(Player.player2 != null)
			{
				Player.player1.SendMessage("ApplyDamage",5,SendMessageOptions.DontRequireReceiver);
			}
			timefromLastShot = 0;
		}
		timefromLastShot += Time.deltaTime;
	}
}

