//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class MeleeEnemy : Enemy
{
	private float meleeRange = 10;
	
	void Update () 
	{
		float distanceFromPlayer = (player.transform.position - transform.position).magnitude;

		if(distanceFromPlayer < meleeRange && timefromLastShot > weapon.fireRate)
		{
			playerClass.SendMessage("ApplyDamage",5,SendMessageOptions.DontRequireReceiver);
			timefromLastShot = 0;
		}
		timefromLastShot += Time.deltaTime;
	}
}

